### ISSUE TITLE
Query SQL

### ISSUE THREAD

**Issue by myarfa** [Akir4d/JACAT#2]
Galat
Query SQL: Dokumentasi

#
# activation feature upgrade
#
ALTER TABLE `admin_users`
  ADD     COLUMN `activation_selector`  varchar(255) AFTER `email`,
  MODIFY  COLUMN `activation_code`      varchar(255)
MySQL menyatakan: Dokumentasi

#1146 - Table 'modular.admin_users' doesn't exist

**Comment by Akir4d** [comment]
That error refers to a database table without admin_users, from what template you try to upgrade?

**Comment by Akir4d** [comment]
Changed way to setup and upgrade database!
